# Generated by Django 5.1.3 on 2025-11-25 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('product_type', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('budget', models.CharField(blank=True, max_length=100)),
                ('message', models.TextField(blank=True)),
                ('reference_images', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('QUALIFIED', 'Qualified'), ('SCOPE_LOCKED', 'Scope Locked'), ('PI_SENT', 'PI Sent'), ('ORDER_CONFIRMED', 'Order Confirmed'), ('LOST', 'Lost')], default='NEW', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Lead History',
                'verbose_name_plural': 'Lead Histories',
                'ordering': ['-timestamp'],
            },
        ),
    ]
