# Generated by Django 5.1.3 on 2025-11-25 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lead',
            name='user',
            field=models.ForeignKey(blank=True, help_text='The buyer who created this lead (if logged in)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_leads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leadhistory',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='leads.lead'),
        ),
        migrations.AddField(
            model_name='leadhistory',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
