# Generated by Django 5.1.3 on 2025-11-25 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approvals', models.JSONField(blank=True, default=dict, help_text='Pre-production approvals')),
                ('stages', models.JSONField(blank=True, default=dict, help_text='Production stages progress')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='production', to='orders.order')),
            ],
            options={
                'verbose_name': 'Production',
                'verbose_name_plural': 'Productions',
            },
        ),
        migrations.CreateModel(
            name='QCReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('INLINE', 'Inline QC'), ('TOP', 'TOP QC'), ('FINAL', 'Final QC')], max_length=10)),
                ('status', models.CharField(choices=[('PASS', 'Pass'), ('FAIL', 'Fail'), ('PENDING', 'Pending')], default='PENDING', max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('aql', models.DecimalField(decimal_places=2, default=2.5, help_text='Acceptable Quality Level', max_digits=4)),
                ('defects', models.JSONField(blank=True, default=list)),
                ('report_url', models.FileField(blank=True, upload_to='qc_reports/')),
                ('images', models.JSONField(blank=True, default=list, help_text='Array of image URLs')),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qc_reports', to='production.production')),
            ],
            options={
                'verbose_name': 'QC Report',
                'verbose_name_plural': 'QC Reports',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courier', models.CharField(blank=True, max_length=255)),
                ('tracking_number', models.CharField(blank=True, max_length=255)),
                ('etd', models.DateField(blank=True, help_text='Estimated Time of Departure', null=True)),
                ('eta', models.DateField(blank=True, help_text='Estimated Time of Arrival', null=True)),
                ('invoice_url', models.FileField(blank=True, upload_to='shipment/invoices/')),
                ('packing_list_url', models.FileField(blank=True, upload_to='shipment/packing/')),
                ('awb_url', models.FileField(blank=True, upload_to='shipment/awb/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('production', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipment', to='production.production')),
            ],
            options={
                'verbose_name': 'Shipment',
                'verbose_name_plural': 'Shipments',
            },
        ),
    ]
