# Generated by Django 5.1.3 on 2025-11-25 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Costing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style_name', models.CharField(max_length=255)),
                ('style_number', models.CharField(blank=True, max_length=100)),
                ('fabric_cost', models.DecimalField(decimal_places=2, help_text='Cost per unit (e.g., per meter)', max_digits=10)),
                ('fabric_consumption', models.DecimalField(decimal_places=2, help_text='Units consumed per garment', max_digits=8)),
                ('trim_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cm_cost', models.DecimalField(decimal_places=2, help_text='Cut & Make cost', max_digits=10)),
                ('packing_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('overhead_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('profit_margin', models.DecimalField(decimal_places=2, default=20, help_text='Profit margin percentage', max_digits=5)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('exw_price', models.DecimalField(decimal_places=2, editable=False, max_digits=10, null=True)),
                ('total_price', models.DecimalField(decimal_places=2, editable=False, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Costing',
                'verbose_name_plural': 'Costings',
                'ordering': ['-created_at'],
            },
        ),
    ]
