# Generated by Django 5.1.3 on 2025-11-25 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pi_number', models.CharField(blank=True, max_length=100, unique=True)),
                ('buyer_name', models.CharField(max_length=255)),
                ('buyer_company', models.CharField(blank=True, max_length=255)),
                ('buyer_address', models.TextField(blank=True)),
                ('buyer_email', models.EmailField(max_length=254)),
                ('buyer_phone', models.CharField(blank=True, max_length=20)),
                ('commercial_term', models.CharField(choices=[('EXW', 'EX Works'), ('FOB', 'Free On Board'), ('CIF', 'Cost, Insurance & Freight'), ('CIP', 'Carriage & Insurance Paid'), ('DDP_AIR', 'DDP Air'), ('DDP_SEA', 'DDP Sea')], default='EXW', max_length=20)),
                ('payment_terms', models.CharField(default='50% Advance, 50% Before Shipment', max_length=255)),
                ('bank_details', models.TextField(blank=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('PI_GENERATED', 'PI Generated'), ('ADVANCE_RECEIVED', 'Advance Received'), ('PRODUCTION', 'In Production'), ('QC_PASSED', 'QC Passed'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PI_GENERATED', max_length=20)),
                ('pi_date', models.DateTimeField(auto_now_add=True)),
                ('advance_date', models.DateTimeField(blank=True, null=True)),
                ('production_start_date', models.DateTimeField(blank=True, null=True)),
                ('shipment_date', models.DateTimeField(blank=True, null=True)),
                ('pi_url', models.FileField(blank=True, upload_to='documents/pi/')),
                ('invoice_url', models.FileField(blank=True, upload_to='documents/invoices/')),
                ('packing_list_url', models.FileField(blank=True, upload_to='documents/packing/')),
                ('awb_url', models.FileField(blank=True, upload_to='documents/awb/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='leads.lead')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style_name', models.CharField(max_length=255)),
                ('style_number', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('size_breakdown', models.CharField(blank=True, help_text='e.g., S:10, M:20, L:15', max_length=255)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='orders.order')),
            ],
        ),
    ]
