# Generated by Django 5.1.3 on 2025-11-25 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('sub_category', models.CharField(max_length=100)),
                ('images', models.JSONField(default=list, help_text='Array of image URLs')),
                ('price_tiers', models.JSONField(default=list, help_text='Array of {minQty, maxQty, price} objects')),
                ('colors', models.JSONField(default=list, help_text='Array of {name, hex, image} objects')),
                ('sizes', models.JSONField(default=list, help_text='Array of size strings')),
                ('moq', models.IntegerField(default=1, help_text='Minimum Order Quantity')),
                ('lead_time', models.CharField(help_text='e.g., "7-15 days"', max_length=100)),
                ('customization', models.JSONField(blank=True, default=list, help_text='Array of customization options (e.g., ["Logo", "Packaging"])')),
                ('specifications', models.JSONField(blank=True, default=dict, help_text='Object with material, fabricType, technics, feature, origin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
            },
        ),
    ]
