# Generated by Django 5.2.4 on 2025-11-29 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bulk_pricing',
            field=models.TextField(blank=True, help_text='Bulk pricing information'),
        ),
        migrations.AddField(
            model_name='product',
            name='certifications',
            field=models.CharField(blank=True, help_text='Certifications', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, help_text='Product material', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='payment_terms',
            field=models.CharField(blank=True, help_text='Payment terms', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='shipping_terms',
            field=models.CharField(blank=True, help_text='Shipping terms', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty',
            field=models.CharField(blank=True, help_text='Warranty information', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='lead_time',
            field=models.CharField(blank=True, help_text='e.g., "7-15 days"', max_length=100),
        ),
    ]
